In [8]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [9]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [10]:
diabetes_dataset = pd.read_csv('diabetes.csv')

In [11]:
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [15]:
heart_dataset = pd.read_csv('heart_disease_uci.csv')

In [7]:
heart_dataset.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [10]:
heart_dataset.shape

(920, 16)

In [11]:
heart_dataset['num'].unique()

array([0, 2, 1, 3, 4])

In [1]:
!pip install pandas-Profiling

Requirement already satisfied: pandas-Profiling in /home/anurag10/anaconda3/lib/python3.9/site-packages (3.6.6)
Requirement already satisfied: ydata-profiling in /home/anurag10/anaconda3/lib/python3.9/site-packages (from pandas-Profiling) (4.1.2)
Requirement already satisfied: scipy<1.10,>=1.4.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (1.9.1)
Requirement already satisfied: pandas!=1.4.0,<1.6,>1.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (1.4.4)
Requirement already satisfied: matplotlib<3.7,>=3.2 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (3.5.2)
Requirement already satisfied: pydantic<1.11,>=1.8.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (1.10.7)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (2.11.3)
Requirement already satisfied: visions[type_image_path]==0.7.5 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (0.7.5)
Requirement already satisfied: numpy<1.24,>=1.16.0 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (1.21.5)
Requirement already satisfied: htmlmin==0.1.12 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (0.12.3)
Requirement already satisfied: requests<2.29,>=2.24.0 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (2.28.1)
Requirement already satisfied: tqdm<4.65,>=4.48.2 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (4.64.1)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (0.11.2)
Requirement already satisfied: multimethod<1.10,>=1.4 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (1.9.1)
Requirement already satisfied: statsmodels<0.14,>=0.13.2 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (0.13.2)
Requirement already satisfied: typeguard<2.14,>=2.13.2 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (2.13.3)
Requirement already satisfied: imagehash==4.3.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from ydata-profiling->pandas-Profiling) (4.3.1)
Requirement already satisfied: PyWavelets in /home/anurag10/anaconda3/lib/python3.9/site-packages (from imagehash==4.3.1->ydata-profiling->pandas-Profiling) (1.3.0)
Requirement already satisfied: pillow in /home/anurag10/anaconda3/lib/python3.9/site-packages (from imagehash==4.3.1->ydata-profiling->pandas-Profiling) (9.2.0)
Requirement already satisfied: attrs>=19.3.0 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-Profiling) (21.4.0)
Requirement already satisfied: networkx>=2.4 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-Profiling) (2.8.4)
Requirement already satisfied: tangled-up-in-unicode>=0.0.4 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-Profiling) (0.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling->pandas-Profiling) (2.0.1)
Requirement already satisfied: cycler>=0.10 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from matplotlib<3.7,>=3.2->ydata-profiling->pandas-Profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from matplotlib<3.7,>=3.2->ydata-profiling->pandas-Profiling) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from matplotlib<3.7,>=3.2->ydata-profiling->pandas-Profiling) (1.4.2)
Requirement already satisfied: packaging>=20.0 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from matplotlib<3.7,>=3.2->ydata-profiling->pandas-Profiling) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from matplotlib<3.7,>=3.2->ydata-profiling->pandas-Profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from matplotlib<3.7,>=3.2->ydata-profiling->pandas-Profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from pandas!=1.4.0,<1.6,>1.1->ydata-profiling->pandas-Profiling) (2022.1)
Requirement already satisfied: joblib>=0.14.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from phik<0.13,>=0.11.1->ydata-profiling->pandas-Profiling) (1.2.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from pydantic<1.11,>=1.8.1->ydata-profiling->pandas-Profiling) (4.3.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from requests<2.29,>=2.24.0->ydata-profiling->pandas-Profiling) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from requests<2.29,>=2.24.0->ydata-profiling->pandas-Profiling) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from requests<2.29,>=2.24.0->ydata-profiling->pandas-Profiling) (1.26.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from requests<2.29,>=2.24.0->ydata-profiling->pandas-Profiling) (2022.9.14)
Requirement already satisfied: patsy>=0.5.2 in /home/anurag10/anaconda3/lib/python3.9/site-packages (from statsmodels<0.14,>=0.13.2->ydata-profiling->pandas-Profiling) (0.5.2)
Requirement already satisfied: six in /home/anurag10/anaconda3/lib/python3.9/site-packages (from patsy>=0.5.2->statsmodels<0.14,>=0.13.2->ydata-profiling->pandas-Profiling) (1.16.0)

In [2]:
import seaborn as sns

In [6]:
from pandas_profiling import ProfileReport

In [12]:
profile = ProfileReport(diabetes_dataset,explorative=True)

In [14]:
profile.to_file('diabetes_EDA.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [16]:
profile = ProfileReport(heart_dataset,explorative=True)

In [17]:
profile.to_file('Heart_EDA.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]